version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    env_file:
      - ./backend/.env 
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PORT}:9000"
    command: sh -c "./wait-for-it.sh postgres:5432 -- npm run migration:run && npm start"

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  postgres-data:
